### ISSUE TITLE
Prepare Release v1.3.0

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#352]
## Task

**Description:**
Prepare a release 1.3.0 and push new tag to `main` branch.

**Subtasks:**
- [ ] Merge all related PRs
- [ ] Change version in POM file
- [ ] Prepare release notes
- [ ] Push a new tag
